import {Timestamp} from "firebase-admin/firestore";

/**
 * Represents a feed item in the Firestore collection
 */
export interface FeedItem {
  /** Auto-generated Firestore Document ID (Used as the RSS item guid) */
  id: string;
  /** The original URL that was passed to the endpoint */
  url: string;
  /** The human-readable title generated by the Gemini API */
  title: string;
  /** The concise summary generated by the Gemini API */
  description: string;
  /** The time the URL was added (used for sorting the feed) */
  pubDate: Timestamp;
}

/**
 * Input data for creating a new feed item (without generated fields)
 */
export interface FeedItemInput {
  url: string;
  title: string;
  description: string;
}

/**
 * Response structure from Gemini API
 */
export interface GeminiParseResponse {
  title: string;
  description: string;
}

/**
 * Request body for the ingestion endpoint
 */
export interface IngestionRequest {
  url: string;
  token?: string;
}

/**
 * Response from the ingestion endpoint
 */
export interface IngestionResponse {
  success: boolean;
  message: string;
  feedUrl?: string;
  itemId?: string;
}
